repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        types_or: [css, javascript]
        additional_depdencies:
            - prettier@2.8.4
