version: '3.8'

services:
  backend-django:
    build: ./src/backend/teaser
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8069:8000
    volumes:
      - ./src/backend/teaser:/app
    env_file:
      - .backend.env
    depends_on:
      - db
    networks:
      - teaser-network
  frontend:
    build: ./src/frontend/teaser
    command: npm run start
    ports:
      - 8081:8081
      - 42069:42069
    env_file:
      - .frontend.env
    volumes:
      - ./src/frontend/teaser:/app
      - /app/node_modules
    networks:
      - teaser-network
  db:
    image: postgres:15.2
    volumes:
      - ./data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=teaseruser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=teaser
    networks:
      - teaser-network
  nginx:
    restart: unless-stopped
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend-django
    networks:
      - teaser-network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


volumes:
  static_volume:
networks:
  teaser-network:
