version: '3.8'

services:
  backend-django:
    build: ./src/backend/teaser
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src/backend/teaser:/app
    env_file:
      - .backend.env
    depends_on:
      - db
    networks:
      - teaser-network
  frontend:
    build: ./src/frontend/teaser
    command: npm run start
    ports:
      - 42069:42069
    env_file:
      - .frontend.env
    volumes:
      - ./src/frontend/teaser:/app
      - /app/node_modules
    networks:
      - teaser-network
  db:
    image: postgres:15.2
    volumes:
      - ./data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=teaseruser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=teaser
    networks:
      - teaser-network



networks:
  teaser-network:
