version: '3.8'

services:
  backend-django:
    build: ./src/backend/teaser
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src/backend/teaser:/app
    env_file:
      - .backend.env
    networks:
      - teaser-network
  frontend:
    build: ./src/frontend/teaser
    command: npm start --clear
    ports:
      - 666:666
    volumes:
      - ./src/frontend/teaser:/app
    networks:
      - teaser-network



networks:
  teaser-network:
