version: '3.8'

services:
  backend-django:
    build: ./src/backend/wocchit
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src/backend/wocchit:/app
    env_file:
      - .backend.env
    networks:
      - memefeed-network
  frontend:
    build: ./src/frontend
    command: npm run dev
    ports:
      - 666:666
    volumes:
      - ./src/frontend:/app
    networks:
      - memefeed-network



networks:
  memefeed-network:
