export const HOMESCREEN_FOOTER_HEIGHT = 48;
export const VIDEO_PORTRAIT = 0;
export const VIDEO_LANDSCAPE = 1;
export const VIEWABILITY_CONFIG_THRESHOLD = 90;
export const TEXT_INPUT_LABEL_FONTWEIGHT = 18;
export const REGISTER_BUTTON_COLOR = "#db133e";
