# Generated by Django 4.1.6 on 2023-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaigeneratedimagesmodel',
            name='file_path',
            field=models.URLField(max_length=500),
        ),
    ]
