# Generated by Django 4.1.6 on 2023-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_openaigeneratedimagesmodel_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='upload_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='post_type',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostTypesModel',
        ),
    ]
