# Generated by Django 4.1.6 on 2023-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookmarkedpostsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='reddit_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddIndex(
            model_name='postsmodel',
            index=models.Index(fields=['description'], name='core_postsm_descrip_ad8e19_idx'),
        ),
    ]
