# Generated by Django 4.1.6 on 2023-03-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventmetricsmodel_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokenModel',
            fields=[
                ('token_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('teaser_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teaserusermodel')),
            ],
        ),
    ]
