# Generated by Django 4.1.6 on 2023-04-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postsmodel_reddit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='reddit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
