# Generated by Django 4.1.6 on 2023-04-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_postsmodel_title_postsmodel_is_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsmodel',
            name='author',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
        migrations.AddField(
            model_name='songsmodel',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songsmodel',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original url the song was downloaded from'),
        ),
        migrations.AddField(
            model_name='songsmodel',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='song_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.songsmodel'),
        ),
    ]
