# Generated by Django 4.1.6 on 2023-03-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authtokenmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaserusermodel',
            old_name='user_model',
            new_name='user_id',
        ),
    ]
