# Generated by Django 4.1.6 on 2023-04-17 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_songsmodel_author_songsmodel_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='video_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID used by bunny.net for categorizing videos'),
        ),
    ]
