# Generated by Django 4.1.6 on 2023-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categoriesmodel_options_categoriesmodel_alias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsmodel',
            options={'ordering': ('status',)},
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='thumbnail_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='video_mode',
            field=models.IntegerField(choices=[(0, 'Portrait'), (1, 'Landscape')], default=0),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='video_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Teaser Type'), (1, 'Q And A Type')], default=0),
        ),
    ]
