# Generated by Django 4.1.6 on 2023-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postsmodel_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='video_id',
            field=models.UUIDField(blank=True, editable=False, help_text='UUID used by bunny.net for categorizing videos', null=True),
        ),
    ]
