# Generated by Django 4.1.6 on 2023-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_postsmodel_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='is_uploaded',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Not Started'), (0, 'Queued'), (1, 'Processing'), (2, 'Encoding'), (3, 'Finished'), (4, 'Resolution Finished'), (5, 'Failed'), (6, 'Presigned Upload Started'), (7, 'Presigned Upload Finished'), (8, 'Presigned Upload Failed')], default=-1),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='video_id',
            field=models.UUIDField(blank=True, help_text='UUID used by bunny.net for categorizing videos', null=True),
        ),
        migrations.AddIndex(
            model_name='postsmodel',
            index=models.Index(fields=['video_id'], name='core_postsm_video_i_0a7f52_idx'),
        ),
        migrations.AddIndex(
            model_name='songsmodel',
            index=models.Index(fields=['title', 'author'], name='core_songsm_title_d0ef85_idx'),
        ),
    ]
