# Generated by Django 4.1.6 on 2023-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_postsmodel_options_postsmodel_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
