# Generated by Django 4.1.6 on 2023-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_postsmodel_is_uploaded_postsmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='has_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='post_data',
            field=models.JSONField(help_text='data: {urls, categories, thumbnails, ...}, question: {question_text, voiceover_url}'),
        ),
        migrations.AddIndex(
            model_name='usercategoriesmodel',
            index=models.Index(fields=['user_id'], name='core_userca_user_id_caf0e9_idx'),
        ),
    ]
