# Generated by Django 4.1.6 on 2023-05-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postsmodel_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='is_nsfw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='postsmodel',
            index=models.Index(fields=['status'], name='core_postsm_status_a6a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='postsmodel',
            index=models.Index(fields=['is_nsfw'], name='core_postsm_is_nsfw_83ffa2_idx'),
        ),
    ]
