# Generated by Django 4.1.6 on 2023-04-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postsmodel_has_comments_alter_postsmodel_post_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriesmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postsmodel')),
            ],
        ),
    ]
