# Generated by Django 4.1.6 on 2023-05-07 06:42

from django.db import migrations, models
from core.models.post_models import PostsModel

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postsmodel_is_nsfw_and_more'),
    ]
    def denormalize_nfc_username_field(apps, schema_editor):
        for post in PostsModel.objects.all():
            post.nfc_username = post.user_id.nfc_username
            post.save()

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='nfc_username',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(denormalize_nfc_username_field)
    ]
