# Generated by Django 4.1.6 on 2023-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postcategoriesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='description',
            field=models.CharField(default='Add a bio', max_length=200),
        ),
    ]
