# Generated by Django 4.1.6 on 2023-05-07 06:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postsmodel_nfc_username'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postsmodel',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('description', 'nfc_username', django.db.models.functions.comparison.Cast('post_data__data__categories', models.CharField()), config='english'), name='search_vector_idx'),
        ),
    ]
