# Generated by Django 4.1.6 on 2023-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postsmodel_search_vector_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmetricsmodel',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Login'), (2, 'Register'), (3, 'Search')], default=0),
        ),
        migrations.DeleteModel(
            name='EventMetricsTypeModel',
        ),
    ]
