# Generated by Django 4.1.6 on 2023-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_eventmetricsmodel_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmetricsmodel',
            options={'ordering': ['event_type', '-timestamp']},
        ),
        migrations.AddIndex(
            model_name='eventmetricsmodel',
            index=models.Index(fields=['event_type', 'timestamp'], name='core_eventm_event_t_ca7e79_idx'),
        ),
    ]
