# Generated by Django 4.1.6 on 2023-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sharedpostsmodel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarkedpostsmodel',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='likedpostsmodel',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sharedpostsmodel',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userpostactivitiesmodel',
            unique_together={('user_id', 'post_id')},
        ),
        migrations.AddIndex(
            model_name='bookmarkedpostsmodel',
            index=models.Index(fields=['user_id', 'post_id'], name='core_bookma_user_id_e46df2_idx'),
        ),
        migrations.AddIndex(
            model_name='commentsmodel',
            index=models.Index(fields=['user_id', 'post_id', 'comment_text'], name='core_commen_user_id_d6258d_idx'),
        ),
        migrations.AddIndex(
            model_name='likedpostsmodel',
            index=models.Index(fields=['user_id', 'post_id'], name='core_likedp_user_id_f027c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedpostsmodel',
            index=models.Index(fields=['user_id', 'post_id'], name='core_shared_user_id_6e1720_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostactivitiesmodel',
            index=models.Index(fields=['user_id', 'post_id'], name='core_userpo_user_id_b12788_idx'),
        ),
    ]
