# Generated by Django 4.1.6 on 2023-06-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_commentpathsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpathsmodel',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ancestor', to='core.commentsmodel'),
        ),
        migrations.AlterField(
            model_name='commentpathsmodel',
            name='descendent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descendent', to='core.commentsmodel'),
        ),
    ]
