# Generated by Django 4.1.6 on 2023-06-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_commentpathsmodel_ancestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmetricsmodel',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Login'), (2, 'Register'), (3, 'Search'), (4, 'Like'), (5, 'Bookmark'), (6, 'Share'), (7, 'Comment'), (8, 'Comment Like')], default=0),
        ),
        migrations.CreateModel(
            name='LikedCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.commentsmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.teaserusermodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='likedcommentsmodel',
            index=models.Index(fields=['user_id', 'comment_id', 'is_liked'], name='core_likedc_user_id_72e167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likedcommentsmodel',
            unique_together={('user_id', 'comment_id')},
        ),
    ]
