# Generated by Django 4.1.6 on 2023-06-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_eventmetricsmodel_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='has_replies',
            field=models.BooleanField(default=False),
        ),
    ]
