# Generated by Django 4.1.6 on 2023-06-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_commentsmodel_has_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpathsmodel',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestor', to='core.commentsmodel'),
        ),
        migrations.AlterField(
            model_name='commentpathsmodel',
            name='descendent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendent', to='core.commentsmodel'),
        ),
        migrations.AlterField(
            model_name='likedcommentsmodel',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.commentsmodel'),
        ),
    ]
