# Generated by Django 4.1.6 on 2023-06-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_commentpathsmodel_ancestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaserusermodel',
            name='profile_photo_url',
            field=models.URLField(blank=True, default='http://teasernsfw.b-cdn.net/teaser-32x32.png'),
        ),
    ]
