# Generated by Django 4.1.6 on 2023-06-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_postreportsmodel_commentreportsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsmodel',
            options={'ordering': ('status', '-created_at')},
        ),
    ]
