# Generated by Django 4.1.6 on 2023-06-14 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_postreportsmodel_commentreportsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsmodel',
            options={'ordering': ('status', '-created_at')},
        ),
        migrations.AlterField(
            model_name='postreportsmodel',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postsmodel'),
        ),
    ]
