CATEGORIES_ALIASES = {
    "Amateur": ["Amateur", "Homemade", "Camming", "First Person"],
    "Ethnicity": [
        "Ethnicity",
        "Asian",
        "Brazilian",
        "Chinese",
        "Ebony",
        "European",
        "Interracial",
        "Indian",
        "Interracial",
        "Japanese",
        "Latino",
        "Russian",
    ],
    "Hentai": ["Hentai", "Anime", "Western Cartoon", "VTuber"],
    "MILF": ["MILF", "Stepmom", "Mature", "Housewife"],
    "Gay": ["Gay", "Daddy", "Twink"],
    "Lesbian": ["Lesbian", "Strapon", "Fingering"],
    "Transgender": ["Transgender", "Futanari", "Shemale"],
    "Funny": ["Funny", "Comedy", "Memes", "Shitposting"],
    "Romantic": ["Romantic", "Dating", "Dinner", "No Sex"],
    "Group": ["Group", "Threesome", "Gangbang"],
    "Femboy": ["Femboy", "Crossdressing", "Sissy"],
    "Femdom": ["Femdom", "Pegging"],
    "Oral": ["Oral", "Blowjob", "Cunnilingus"],
    "Anal": ["Anal"],
    "How To / Educational": ["How To / Educational", "Tutorials"],
    "Social Media": ["Social Media", "Tiktok", "Snapchat", "Instagram"],
    "Roleplay": ["Roleplay", "Cosplay", "Teacher", "College", "Maid"],
    "Fitness": ["Fitness", "Workout", "Sports", "Wrestling"],
    "Dance": ["Dance", "Tiktok", "Ballroom"],
    "Body Type": ["Body Type", "Petite", "Curvy"],
    "Pornstars": ["Pornstars", "Johnny Sins", "Riley Reid"],
    "Challenges": ["Challenges", "Try Not To Cum Challenge", "NNN"],
    "Video Games": ["Video Games", "Overwatch", "Fortnite", "League of Legends"],
    "VR / AR": ["VR / AR", "Mobile VR"],
    "Pop Culture": ["Pop Culture", "Will Smith Slap"],
    "Feet": ["Feet", "Foot Fetish", "Boots"],
    "Bondage": ["Bondage", "Blindfold", "Handcuffs", "Rope Bondage", "BDSM"],
    "Other": ["Other", "Furry", "Masturbation", "Fashion", "Public", "Parody"],
}


"""
Platforms:
- redgifs video
- imgur images + video
"""
ALL_CATEGORIES_TEMP = {
    "Homemade": "RealHomePorn",
    "Camming": "CamSluts",
    "First Person": "POV",
    "Asian": "AsianPorn",
    "Brazilian": "BrazilianPorn",
    "Chinese": "NSFW_China",
    "Ebony": "gonewildcolor",
    "European": "whoreurope",
    "Interracial": "damngoodinterracial",
    "Indian": "IndianPorn",
    "Japanese": "japanese_adult_video",
    "Latino": "Latina_Porn",
    "Russian": "easterneuropeangirls",
    "Anime": "hentai",
    "Western Cartoon": "CartoonPorn",
    "VTuber": "LewdVtubers",
    "Stepmom": "sonmom",
    "Mature": "hotGILFs",
    "Housewife": "HotInTheKitchen",
    "Daddy": "DadsGoneWild",
    "Twink": "boypussy",
    "Strapon": "straponlesbians",
    "Fingering": "Fingering",
    "Futanari": "Futa_Vids",
    "Shemale": "Shemale_vids",
    "Comedy": "NSFWFunny",
    "Memes": "NSFWMemes",
    "Shitposting": "shitposting",
    "Dating": "passionx",
    "Dinner": "",
    "No Sex": "SexyButNotPorn",
    "Threesome": "Xsome",
    "Gangbang": "amateur_threesomes",
    "Crossdressing": "CDporn",
    "Sissy": "sissyhypno",
    "Pegging": "Pegging",
    "Blowjob": "Blowjobs",
    "Cunnilingus": "cunnilingus",
    "Tutorials": "educationalnudity",
    "Tiktok": "tiktokporn",
    "Snapchat": "slutsofsnapchat",
    "Instagram": "SocialMediaSluts",
    "Cosplay": "CosplayPornVideos",
    "Teacher": "teachersgonewild",
    "College": "collegesluts",
    "Maid": "frenchmaid",
    "Workout": "Workoutgonewild",
    "Sports": "Ohlympics",
    "Wrestling": "Sexfight",
    "Ballroom": "nakedgirlsdancing",
    "Petite": "TinyNymphs",
    "Curvy": "curvy",
    "Johnny Sins": "",
    "Riley Reid": "RileyReid",
    "Try Not To Cum Challenge": "joi",
    "NNN": "nonutnovember",
    "Overwatch": "Overwatch_Porn",
    "Fortnite": "FortnitePornOnly",
    "League of Legends": "Rule34LoL",
    "Mobile VR": "",
    "Will Smith Slap": "",
    "Foot Fetish": "VerifiedFeetGifs",
    "Boots": "SexyGirlsInBoots",
    "Blindfold": "Blindfolded",
    "Handcuffs": "predicamentbondage",
    "Rope Bondage": "ropebondage",
    "BDSM": "Bondage_Porn",
    "Furry": "yiff",
    "Masturbation": "girlsmasturbating",
    "Fashion": "NSFWfashion",
    "Public": "PublicSexPorn",
    "Parody": "PornoMemes",
    "Amateur": "AmateurPorn",
    "Ethnicity": "",
    "Hentai": "nsfw_zhentai",
    "MILF": "milfcumsluts",
    "Gay": "AmateurGayPorn",
    "Lesbian": "lesbians",
    "Transgender": "Shemaleselffacials",
    "Funny": "FunnySexPorn",
    "Romantic": "romanticxxx",
    "Group": "groupsex",
    "Femboy": "FemBoys",
    "Femdom": "Femdom",
    "Oral": "OralSexPorn",
    "Anal": "anal",
    "How To / Educational": "Sexedporn",
    "Social Media": "tiktokporn",
    "Roleplay": "",
    "Fitness": "fitgirlsfucking",
    "Dance": "striptease",
    "Body Type": "",
    "Pornstars": "PornStars",
    "Challenges": "HotwifeChallenges",
    "Video Games": "SourcePornMaker",
    "VR / AR": "oculusNSFW",
    "Pop Culture": "PornMusicVids",
    "Feet": "FootFetish",
    "Bondage": "Bondage",
    "Other": "",
}


def validate_categories(categories):
    # TODO: Validate categories are valid in db
    for category in categories:
        if not ALL_CATEGORIES_TEMP[category]:
            raise ValueError  # TODO:
